language: python

branches:
  only:
    - master

script: python fetch_meo_test.py

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "www.cinefilopobre.com"

